### ISSUE TITLE
testpath breaks pip

### ISSUE THREAD

**Issue by ltupin** [jupyter/testpath#16]
Hi there,

Are you aware that it seems testpath breaks pip ? 

Please have a look on thoses issues:
https://github.com/conda-forge/testpath-feedstock/issues/7
https://github.com/pypa/pip/issues/5839

**Comment by takluyver** [comment]
This should now be resolved by a newer version of testpath (the fix was actually in Flit), and I've opened a pull request on Flit to be less delicate when there are problems with already installed packages:

https://github.com/pypa/pip/pull/5842
