### ISSUE TITLE
tar-ball for pypi

### ISSUE THREAD

**Issue by arunpersaud** [jupyter/testpath#6]
Hi

is it possible to upload a tar-ball again on pypi? The source code is used to build packages for linux distributions, e.g. openSUSE creates their rpms from source distributions and I cannot package a .whl file.

Thanks

Arun

**Comment by takluyver** [comment]
You can get source tarballs from e.g. https://github.com/jupyter/testpath/archive/0.3.tar.gz . I'm not really interested in building Python sdists.

**Comment by arunpersaud** [comment]
ok. thanks for the quick reply
