### ISSUE TITLE
sync sorc.tar.gz with PyPi

### ISSUE THREAD

**Issue by epifanio** [jupyter/testpath#9]
Hi, is it possible to upload the src.tar.gz for the latest version on PyPI?
at the moment there is only the `whl` or an older tarball (`0.1`).

I need to fetch the source code programmatically so I use `pip` to get the source code :  

```
pip download --no-binary :all: testpath
```
will download: `testpath-0.1.tar.gz` while I was expecting to receive the latest version available from the `doap.xml` description, which is `0.3` https://pypi.python.org/pypi/testpath

**Comment by Carreau** [comment]
No, because the tgz does not have a setup.py, which means that the `src.tar.gz` cannot be installed by pip.

Though latest master of flit can generate a `setup.py`, so it might be possible with next version of testpath.

**Comment by takluyver** [comment]
Let's use this as a test case for the new machinery in flit! I've just uploaded a new release with a tarball.

@epifanio that command should now get you `testpath-0.3.1.tar.gz` . Can you confirm that that does what you want?

**Comment by takluyver** [comment]
Closing this on the assumption that the tarball there now works. Please open a new issue if there are problems with it.

**Comment by epifanio** [comment]
@takluyver Thanks! it works great now. sorry for the late reply.
